from ultralytics import YOLO

def get_train_12obb_args():
    return {
    'task': 'obb',
    'mode': 'train',
    'model': 'yolo12n-obb.yaml',
    'pretrained':False,
    'data': 'DOTAv1.0.yaml',
    'epochs': 200,
    'time': None,
    'patience': 50,
    'batch': 32,
    'imgsz': 1024,
    'save': True,
    'save_period': -1,
    'cache': False,
    'device': 6,
    'workers': 8,
    'project': 'YOLO12-OBB',
    'name': 'nano',
    'exist_ok': True,
    'optimizer': 'auto',
    'verbose': True,
    'seed': 0,
    'deterministic': True,
    'single_cls': False,
    'rect': False,
    'cos_lr': False,
    'close_mosaic': 0,
    'resume': False,
    'amp': True,
    'fraction': 1.0,
    'profile': False,
    'freeze': None,
    'multi_scale': False,
    'overlap_mask': True,
    'mask_ratio': 4,
    'dropout': 0.0,
    'val': True,
    'split': 'val',
    'save_json': True,
    'save_hybrid': False,
    'conf': 0.01,
    'iou': 0.7,
    'max_det': 300,
    'half': False,
    'dnn': False,
    'plots': True,
    'source': None,
    'vid_stride': 1,
    'stream_buffer': False,
    'visualize': False,
    'augment': False,
    'agnostic_nms': False,
    'classes': None,
    'retina_masks': False,
    'embed': None,
    'show': False,
    'save_frames': False,
    'save_txt': True,
    'save_conf': True,
    'save_crop': False,
    'show_labels': True,
    'show_conf': True,
    'show_boxes': True,
    'line_width': None,
    'format': 'torchscript',
    'keras': False,
    'optimize': False,
    'int8': False,
    'dynamic': False,
    'simplify': False,
    'opset': None,
    'workspace': 4,
    'nms': False,
    'lr0': 0.01,
    'lrf': 0.01,
    'momentum': 0.937,
    'weight_decay': 0.0005,
    'warmup_epochs': 3.0,
    'warmup_momentum': 0.8,
    'warmup_bias_lr': 0.0,
    'box': 7.5,
    'cls': 0.5,
    'dfl': 0.75,
    'pose': 12.0,
    'kobj': 1.0,
    'label_smoothing': 0.0,
    'nbs': 64,
    'hsv_h': 0.015,
    'hsv_s': 0.7,
    'hsv_v': 0.4,
    'degrees': 180,
    'translate': 0.1,
    'scale': 0.9,
    'shear': 0.0,
    'perspective': 0.0,
    'flipud': 0.5,
    'fliplr': 0.5,
    'bgr': 0.0,
    'mosaic': 1.0,
    'mixup': 0.1,
    'copy_paste': 0.0,
    'copy_paste_mode': 'flip',
    'auto_augment': 'randaugment',
    'erasing': 0.4,
    'crop_fraction': 1.0,
    'cfg': None,
    'tracker': 'botsort.yaml'
    }

if __name__=="__main__":
    args = get_train_12obb_args()
    #数据结构：函数get_train_12obb_args()返回一个字典

    model=YOLO(args['model'])
    model.load("pretrained/yolo11n-obb.pt")  

    model.train(**args)
    
